name: Node CI

on:
  push:
    branches:
    - master
    - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'
        registry-url: 'https://registry.npm.taobao.org'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
